import type { GmArchetype, GmArchetypeName } from '../types/ai.js';

export const GM_ARCHETYPES: Record<GmArchetypeName, GmArchetype> = {
  analytics_architect: {
    name: 'analytics_architect',
    displayName: 'Analytics Architect',
    description: 'Data-forward GM who maximises comp picks, efficiency, and scheme fit.',
    weights: {
      analyticsReliance: 90,
      scoutingReliance: 70,
      draftPriority: 80,
      freeAgencyAggression: 45,
      tradeAggression: 55,
      capConservatism: 75,
      riskTolerance: 40,
      cultureWeight: 35,
      schemeFitWeight: 85,
      youthBias: 70,
      veteranBias: 35,
      compPickAwareness: 90,
    },
    tendencies: {
      rebuildThreshold: 6,
      contendThreshold: 11,
      coachFiringPatience: 2,
      starPlayerLoyalty: 60,
      draftTradeUpFrequency: 35,
      draftTradeDownFrequency: 70,
      maxDeadMoneyTolerance: 8,
      franchiseTagUsage: 45,
    },
    signatureMoves: [
      'Trades down for surplus value',
      'Lets mid-tier FAs walk for comp picks',
      'Leans on scheme fit grades',
    ],
  },
  culture_commander: {
    name: 'culture_commander',
    displayName: 'Culture Commander',
    description: 'Prioritises locker-room stability, cohesion, and leadership.',
    weights: {
      analyticsReliance: 45,
      scoutingReliance: 70,
      draftPriority: 65,
      freeAgencyAggression: 55,
      tradeAggression: 40,
      capConservatism: 65,
      riskTolerance: 35,
      cultureWeight: 90,
      schemeFitWeight: 60,
      youthBias: 55,
      veteranBias: 70,
      compPickAwareness: 50,
    },
    tendencies: {
      rebuildThreshold: 5,
      contendThreshold: 10,
      coachFiringPatience: 3,
      starPlayerLoyalty: 80,
      draftTradeUpFrequency: 45,
      draftTradeDownFrequency: 40,
      maxDeadMoneyTolerance: 6,
      franchiseTagUsage: 60,
    },
    signatureMoves: [
      'Extends homegrown leaders',
      'Targets high-character free agents',
      'Holds coaches accountable slowly',
    ],
  },
  strategic_rebuilder: {
    name: 'strategic_rebuilder',
    displayName: 'Strategic Rebuilder',
    description: 'Long-horizon planner who stockpiles picks and prioritises youth.',
    weights: {
      analyticsReliance: 65,
      scoutingReliance: 80,
      draftPriority: 95,
      freeAgencyAggression: 30,
      tradeAggression: 60,
      capConservatism: 80,
      riskTolerance: 50,
      cultureWeight: 55,
      schemeFitWeight: 70,
      youthBias: 95,
      veteranBias: 20,
      compPickAwareness: 85,
    },
    tendencies: {
      rebuildThreshold: 7,
      contendThreshold: 12,
      coachFiringPatience: 2,
      starPlayerLoyalty: 45,
      draftTradeUpFrequency: 30,
      draftTradeDownFrequency: 80,
      maxDeadMoneyTolerance: 5,
      franchiseTagUsage: 35,
    },
    signatureMoves: [
      'Trades veterans for picks',
      'Trades down in draft for volume',
      'Keeps cap clean during rebuild',
    ],
  },
  player_centric: {
    name: 'player_centric',
    displayName: 'Player-Centric',
    description: 'Focuses on relationships, morale, and supporting stars.',
    weights: {
      analyticsReliance: 40,
      scoutingReliance: 65,
      draftPriority: 60,
      freeAgencyAggression: 60,
      tradeAggression: 45,
      capConservatism: 55,
      riskTolerance: 35,
      cultureWeight: 85,
      schemeFitWeight: 55,
      youthBias: 60,
      veteranBias: 65,
      compPickAwareness: 45,
    },
    tendencies: {
      rebuildThreshold: 6,
      contendThreshold: 10,
      coachFiringPatience: 2,
      starPlayerLoyalty: 90,
      draftTradeUpFrequency: 50,
      draftTradeDownFrequency: 45,
      maxDeadMoneyTolerance: 7,
      franchiseTagUsage: 70,
    },
    signatureMoves: [
      'Extends core stars early',
      'Chooses coaches for player relationships',
      'Avoids locker-room risk players',
    ],
  },
  aggressive_dealmaker: {
    name: 'aggressive_dealmaker',
    displayName: 'Aggressive Dealmaker',
    description: 'Constantly churns the roster via trades and free agency to win now.',
    weights: {
      analyticsReliance: 55,
      scoutingReliance: 55,
      draftPriority: 50,
      freeAgencyAggression: 90,
      tradeAggression: 95,
      capConservatism: 30,
      riskTolerance: 85,
      cultureWeight: 45,
      schemeFitWeight: 60,
      youthBias: 45,
      veteranBias: 75,
      compPickAwareness: 30,
    },
    tendencies: {
      rebuildThreshold: 4,
      contendThreshold: 9,
      coachFiringPatience: 1,
      starPlayerLoyalty: 55,
      draftTradeUpFrequency: 70,
      draftTradeDownFrequency: 25,
      maxDeadMoneyTolerance: 12,
      franchiseTagUsage: 80,
    },
    signatureMoves: [
      'Trades picks for proven players',
      'Aggressive at trade deadline',
      'Heavy free-agency spender',
    ],
  },
};

export function listArchetypes(): GmArchetype[] {
  return Object.values(GM_ARCHETYPES);
}

export function getArchetypeByName(name: GmArchetypeName): GmArchetype {
  return GM_ARCHETYPES[name];
}
